### PR TITLE
Applied clang-format and stripped all trailing whitespace.

### PR DESCRIPTION
**Pull request by anadon**
The biggest of merges for the smallest of function changes.

### CODE REVIEW

**Comment by anadon** [comment]
@jzmaddock Up for a less frustrating review when you're ready.

**Comment by jzmaddock** [comment]
Is there a .clang-format file with this?

**Comment by anadon** [comment]
There is one pre-existing in the repo.

**Comment by jzmaddock** [comment]
Apologies, I missed the .clang-format file :(

I notice that all C++03 tests are now failing due to "> >" changing to ">>", can this be fixed in the .clang-format file and the files formatted afresh?

Thanks!  John.

**Comment by anadon** [comment]
It certainly can.  I tested on my system, and all tests passed so I didn't notice that.

**Comment by anadon** [comment]
@jzmaddock All is green.

**Pull request merged**
