### PR TITLE
Make comments match actual values of the random graph's number of ver…

### PR DESCRIPTION
**Pull request by svengato**
…tices and probability of edge connection

### CODE REVIEW

**Comment by svengato** [comment]
I noticed the mismatches while working on pull request #315. The changes are only to comments and should not require testing.

**Comment by jeremy-murphy** [comment]
Even better might be to remove the numbers from the comments altogether?

E.g.:
```
    // Generate random graph with N vertices and probability P
    // of edge connection.
    static const size_t N = 20;
    static const double P = 0.1;
```
or
```
    // Generate random graph
    static const size_t N = 20; // Number of vertices
    static const double P = 0.1; // Probability of edge between two vertices
```

**Comment by jeremy-murphy** [comment]
Btw, there is a way to tell the CI not to run, which would be appropriate for these changes, by including some magic text in the commit message. I don't remember exactly what it is... instructions are probably on GitHub somewhere.

**Comment by jeremy-murphy** [comment]
Thanks again!

**Comment by svengato** [comment]
> Btw, there is a way to tell the CI not to run, [...]

Added to my **Things to learn** list. Thanks -

**Pull request merged**
