### PR TITLE
Moved graph_test.hpp from include directory to test directory.

### PR DESCRIPTION
**Pull request by eldiener**

### CODE REVIEW

**Comment by anadon** [comment]
This change looks like it could break things.  Could you please provide a more complete description of the change and tests to verify it does not break anything?

**Comment by eldiener** [comment]
The graph_test.hpp is not used anywhere except in tests and is not documented as part of the graph interface.  There is no reason it should be part of the include directory, The boostdep tool to find dependencies normally searches the include directory of a library but not the test directory.

**Comment by anadon** [comment]
Let me read into this to make sure everything is safe.  If so, I'll include this in the second batch of changes.

**Comment by jzmaddock** [comment]
Looks sensible to me - closing and re-opening to trigger CI.

**Comment by pdimov** [comment]
Did (and just merged) the same PR in #120 without seeing this one, sorry. :-)

**Comment by pdimov** [comment]
(I needed to cut the dependency on Test because it interfered with the CMake config work.)

**Pull request closed without merging**
