### PR TITLE
Null pointer when reindexing edge list

### PR DESCRIPTION
**Pull request by raahlb**
Don't copy value_type if not needed, as source's m_property will be set to null when copied.

See https://svn.boost.org/trac10/ticket/13544.

### CODE REVIEW

**Comment by jeremy-murphy** [comment]
Would it be relatively easy to add a test-case that fails without this fix?

**Comment by raahlb** [comment]
I added a test case. Also added it to the Jamfile.v2. Not used to this test system, so please verify I did it in the right way.

**Comment by anadon** [comment]
I'm helping out with the PR backlog.  Looks like you have a bugfix, test, and no new examples will be needed.  This will be in the first batch of merged PR's.  This is to let you know and help me prioritize PR's.

**Comment by anadon** [comment]
your test file was not included in the test directory.  Make sure you added it to git.

**Comment by anadon** [comment]
I see what happened.  The test you added has a different file name than the test file you added.

**Comment by raahlb** [comment]
Saw now that you had already fixed it yourself. Not super important, but the name "delete edge" is a bit misleading, it's actually a vertex that is being deleted in the test. Sorry about that.

Thanks!

**Comment by jzmaddock** [comment]
Are these changes in https://github.com/boostorg/graph/pull/114?  If so this can be closed now.

**Comment by anadon** [comment]
These changes are in #114 and so this should be closed.

**Pull request closed without merging**
