### PR TITLE
Merge develop into master for 1.80.0 release

### PR DESCRIPTION
**Pull request by jeremy-murphy**
It's my first time merging `develop` into `master`, so can you just make sure I'm not screwing it up please, @jzmaddock ? Thanks!  :)

### CODE REVIEW

**Comment by jzmaddock** [comment]
So far as I can see it looks all good to me, but then I'm down with COVID at present, so I only have half a brain working right now! ;)

**Comment by jeremy-murphy** [comment]
> So far as I can see it looks all good to me, but then I'm down with COVID at present, so I only have half a brain working right now! ;)

Oh no! Let's hope it's your good half!  ;)

Hope you recover soon, John.

**Comment by jeremy-murphy** [comment]
Btw, do I have to do something to update the release notes, or does someone from the release team do that?

**Comment by jzmaddock** [comment]
Ah no, thanks for the reminder I must update my stuff!

You need to submit a PR to https://github.com/boostorg/website/blob/master/feed/history/boost_1_80_0.qbk

**Comment by jeremy-murphy** [comment]
Oh dear, I didn't read your last message properly and I didn't open a PR. I guess I should do so asap?

**Pull request merged**
