### PR TITLE
std::fill with char instead of int (fix issue #180)

### PR DESCRIPTION
**Pull request by jasjuang**
fix issue #180

### CODE REVIEW

**Comment by anadon** [comment]
I'd like to delay this until I get my CI PR finished.

**Comment by glenfe** [comment]
You're replacing 0 with '0'? Why do you believe this is the solution?

**Comment by jasjuang** [comment]
@glenfe It's not about believing it or not. This actually solves the compilation error as indicated in #180.

**Comment by anadon** [comment]
@jasjuang I didn't look at this too closely, but understanding why it fixes it and why it is right is important.

**Comment by jasjuang** [comment]
It is explained in previous threads. `data` is a `unsigned char`, `0` is an int, so there's an implicit type conversion when `std::fill` `data` with `0`, visual studio is strict hence it raises warnings against it. This PR turns `0` to `'0'`, so now it's filled with char and matches type with `data`, so visual studio stops complaining. Is this explanation clear enough?

**Comment by anadon** [comment]
You didn't reference any threads here.  Furthermore, the only way to preserve identical behavior if what you are describing is complete is to use `'\0'`.  So it sounds like there is missing information.  What's up?

**Comment by jasjuang** [comment]
Ok, I made the changes as requested. Nothing special is up, just trying to resolve the bug here.  Everything was explained in #180 and the link at the end of #180. Please merge. Thanks.

**Comment by anadon** [comment]
@glenfe Looks clean.  Would you like to do the honors?

**Comment by glenfe** [comment]
@jasjuang
>  It's not about believing it or not. This actually solves the compilation error as indicated in #180.

Just eliminating a compilation error in the wrong way is *not* a solution. '0' and 0 have two different values. 

If you want an `unsigned char` with a value of 0, you should use an unsigned char with a value of 0. Not one with a value of '0'.

Either `'\0'` or `staric_cast<unsigned char>(0)` would have been appropriate.

**Comment by glenfe** [comment]
@anadon 
> Looks clean. Would you like to do the honors?

Instead of `new unsigned char[n]`  followed by `std::fill` to initialize all the elements to 0, I would prefer using just `new unsigned char[n]()` which would value-initialize all the elements to 0. This would eliminate the need to use `std::fill` entirely.

**Comment by glenfe** [comment]
@anadon To elaborate on my comment above: Right now, the code is doing:

```
explicit two_bit_color_map(std::size_t n, const IndexMap& index = IndexMap())
  : n(n), index(index),
    data(new unsigned char[(n + elements_per_char - 1) / elements_per_char])
{
  // Fill to white
  std::fill(data.get(), data.get() + (n + elements_per_char - 1) / elements_per_char, 0);
}
```

I'm suggesting instead doing:

```
explicit two_bit_color_map(std::size_t n, const IndexMap& index = IndexMap())
  : n(n), index(index),
    data(new unsigned char[(n + elements_per_char - 1) / elements_per_char]())
{ }
```

Note the extra parenthesis `()` in the `new` expression for value-initialization, and the elimination of the `std::fill()` call.

**Comment by anadon** [comment]
@glenfe I was just going through that and figuring out where you intended that.  I did find it before reading this!  I should have caught that.

**Comment by glenfe** [comment]
See d3b157f4656a462beb9ca767838e69b60b393b4b

**Comment by glenfe** [comment]
I've merged d3b157f to develop. We don't need this PR.

**Pull request closed without merging**
